package com.resolum.intiva.platform.finances.domain.model.aggregates;

import com.resolum.intiva.platform.finances.domain.model.commands.CreateRecurringTransactionCommand;
import com.resolum.intiva.platform.finances.domain.model.valueobjects.RecurringFrequency;
import com.resolum.intiva.platform.finances.domain.model.valueobjects.SpendingLimitTargetType;
import com.resolum.intiva.platform.shared.domain.aggregates.AuditableAbstractAggregate;
import com.resolum.intiva.platform.shared.domain.valueobjects.*;
import jakarta.persistence.*;
import jakarta.validation.Valid;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * Aggregate root that represents a recurring instruction capable of generating future transactions.
 *
 * <p>The aggregate does not move balances by itself. Instead, when it becomes due, the application layer
 * reuses the normal {@link Transaction} registration flow so that all existing validations, balance updates,
 * events and spending-limit consumption remain centralized in one place.</p>
 */
@Entity
@Getter
@NoArgsConstructor
@Table(name = "recurring_transactions")
public class RecurringTransaction extends AuditableAbstractAggregate<RecurringTransaction> {

    /**
     * Amount copied into every generated transaction.
     */
    @Embedded
    @Valid
    @AttributeOverrides({
            @AttributeOverride(name = "amount", column = @Column(name = "amount", nullable = false)),
            @AttributeOverride(name = "currencyCode", column = @Column(name = "currency_code", nullable = false))
    })
    private Money amount;

    /**
     * Human-readable description copied into generated transactions.
     */
    @Column(nullable = false)
    private String description;

    /**
     * Owner identifier. For INDIVIDUAL this is a user id; for FAMILY this is a family or group id.
     */
    @Column(nullable = false)
    private Long ownerId;

    /**
     * Ownership scope used by personal and family recurring transactions.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private OwnerTypes ownerType;

    /**
     * Financial account that will receive generated income transactions or pay generated expense transactions.
     */
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "financialAccountId", column = @Column(name = "financial_account_id", nullable = false))
    })
    private FinancialAccountId financialAccountId;

    /**
     * User recorded as the actor when the recurring definition creates a transaction.
     */
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "userId", column = @Column(name = "performed_by_user_id", nullable = false))
    })
    private UserId performedByUserId;

    /**
     * Type of transactions generated by this definition.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionTypes transactionType;

    /**
     * Category assigned to generated transactions.
     */
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false))
    })
    private CategoryId categoryId;

    /**
     * Frequency used to calculate subsequent execution dates.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private RecurringFrequency frequency;

    /**
     * First date on which the recurring definition becomes eligible for execution.
     */
    @Column(nullable = false)
    private LocalDate startDate;

    /**
     * Next date that should be executed by the scheduler.
     */
    @Column(nullable = false)
    private LocalDate nextExecutionDate;

    /**
     * Most recent scheduled execution date that completed successfully.
     */
    private LocalDate lastExecutionDate;

    /**
     * Optional inclusive last date on which the recurring definition may still execute.
     */
    private LocalDate endDate;

    /**
     * Indicates whether the recurring definition is available for scheduler execution.
     */
    @Column(nullable = false)
    private Boolean active;

    @Column(nullable = false)
    private Integer reminderDaysBefore = 3;

    public void updateReminderDays(int reminderDaysBefore) {
        if (reminderDaysBefore != 1 && reminderDaysBefore != 3 && reminderDaysBefore != 7) {
            throw new IllegalArgumentException("reminderDaysBefore must be 1, 3, or 7");
        }
        this.reminderDaysBefore = reminderDaysBefore;
    }

    public RecurringTransaction(CreateRecurringTransactionCommand command) {
        if (command == null) {
            throw new IllegalArgumentException("Command cannot be null");
        }
        if (command.amount() == null) {
            throw new IllegalArgumentException("Amount is required");
        }
        if (command.description() == null || command.description().isBlank()) {
            throw new IllegalArgumentException("Description cannot be null or blank");
        }
        if (command.ownerId() == null || command.ownerType() == null) {
            throw new IllegalArgumentException("Owner information is required");
        }
        if (command.financialAccountId() == null || command.performedByUserId() == null || command.categoryId() == null) {
            throw new IllegalArgumentException("Financial account, performer and category are required");
        }
        if (command.transactionType() == null) {
            throw new IllegalArgumentException("Transaction type is required");
        }
        if (command.transactionType() == TransactionTypes.TRANSFER) {
            throw new IllegalArgumentException("Recurring transfers are not supported");
        }
        if (command.frequency() == null) {
            throw new IllegalArgumentException("Recurring frequency is required");
        }
        if (command.startDate() == null) {
            throw new IllegalArgumentException("Start date is required");
        }

        this.amount = command.amount();
        this.description = command.description();
        this.ownerId = command.ownerId();
        this.ownerType = command.ownerType();
        this.financialAccountId = command.financialAccountId();
        this.performedByUserId = command.performedByUserId();
        this.transactionType = command.transactionType();
        this.categoryId = command.categoryId();
        this.frequency = command.frequency();
        this.startDate = command.startDate();
        this.nextExecutionDate = command.startDate();
        this.endDate = command.endDate();
        this.active = true;

        validateDateRange();
    }

    /**
     * Determines whether the recurring definition should execute on or before the given date.
     *
     * @param date date used by the scheduler to evaluate due executions
     * @return true when the recurring definition is active and nextExecutionDate is due
     */
    public boolean isDue(LocalDate date) {
        if (!Boolean.TRUE.equals(active) || date == null) {
            return false;
        }
        if (endDate != null && nextExecutionDate.isAfter(endDate)) {
            return false;
        }
        return !nextExecutionDate.isAfter(date);
    }

    /**
     * Marks the current scheduled execution as completed and advances the next execution date.
     *
     * <p>If the following date falls beyond the configured end date, the definition deactivates itself so the
     * scheduler stops picking it up.</p>
     */
    public void registerExecution() {
        if (!Boolean.TRUE.equals(active)) {
            throw new IllegalStateException("Recurring transaction is inactive");
        }

        this.lastExecutionDate = this.nextExecutionDate;
        this.nextExecutionDate = calculateNextExecutionDate(this.nextExecutionDate);

        if (endDate != null && this.nextExecutionDate.isAfter(endDate)) {
            this.active = false;
        }
    }

    /**
     * Reactivates the recurring definition.
     *
     * <p>If the definition was exhausted because the next execution date moved beyond endDate, the next execution
     * date is rewound to endDate so that a manual reactivation still has a meaningful schedule anchor.</p>
     */
    public void activate() {
        if (endDate != null && nextExecutionDate.isAfter(endDate)) {
            this.nextExecutionDate = endDate;
        }
        this.active = true;
    }

    /**
     * Deactivates the recurring definition so the scheduler ignores it.
     */
    public void deactivate() {
        this.active = false;
    }

    /**
     * Calculates the next execution date using the configured cadence.
     *
     * @param baseDate current scheduled execution date
     * @return following scheduled execution date
     */
    private LocalDate calculateNextExecutionDate(LocalDate baseDate) {
        return switch (frequency) {
            case DAILY -> baseDate.plusDays(1);
            case WEEKLY -> baseDate.plusWeeks(1);
            case MONTHLY -> baseDate.plusMonths(1);
            case ANNUAL -> baseDate.plusYears(1);
        };
    }

    /**
     * Validates that the configured date range is chronologically valid.
     */
    private void validateDateRange() {
        if (endDate != null && endDate.isBefore(startDate)) {
            throw new IllegalArgumentException("End date cannot be before start date");
        }
    }
}
